#!/usr/bin/env python
# -*- python;  coding: utf-8  -*-
#########################################################################
# notmuch-client: an enhanced client for the notmuch mail system        #
#                                                                       #
# Copyright © 2011 Jesse Rosenthal                                      #
#                                                                       #
# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see http://www.gnu.org/licenses/ .  #
#                                                                       #
# Author: Jesse Rosenthal <jrosenthal@jhu.edu>                          #
#########################################################################



from nmclient import NotmuchCommand, NotmuchClientConfig, \
    NotmuchClientConfigError, CONFIG_LOCATION
from ConfigParser import MissingSectionHeaderError
import sys
import os

if __name__ == "__main__":
    if os.path.isfile(CONFIG_LOCATION):
        try:
            nmconfig = NotmuchClientConfig(CONFIG_LOCATION)
        except MissingSectionHeaderError:
               sys.stderr.write("Couldn't read config file at %s\n. Aborting" % 
                                CONFIG_LOCATION)
               sys.exit(1)
    else:
        nmconfig = NotmuchClientConfig()
    
    try:
        if nmconfig.remote:
            try:
                if not os.path.isdir(nmconfig.cache):
                    os.mkdir(nmconfig.cache)
            except OSError:
                sys.stdout.write("Can't make cache file at %s" % nmconfig.cache)
        args = sys.argv[1:]
        command = NotmuchCommand.make_command(nmconfig, args)
        processes = command.run()
    except NotmuchClientConfigError as err:
        sys.stderr.write("Problem reading config file:\n%s" % err)
        sys.exit(1)

    if isinstance(processes, str):
        sys.stdout.write(processes)
        sys.exit(0)

    for proc in processes:
        while True:
            nextline = proc.stdout.readline()
            if (nextline == '' and  proc.poll != None):
                break
            sys.stdout.write(nextline)
            sys.stdout.flush()

    sys.stderr.write(process.stderr.read())
    sys.stderr.flush()
    sys.exit(0)

