#!/usr/bin/env python
# -*- python -*-

from nmclient import NotmuchCommand, NotmuchClientConfig, CONFIG_LOCATION
from ConfigParser import MissingSectionHeaderError
import sys
import os

if __name__ == "__main__":
    if os.path.isfile(CONFIG_LOCATION):
        try:
            nmconfig = NotmuchClientConfig(CONFIG_LOCATION)
        except MissingSectionHeaderError:
               sys.stderr.write("Couldn't read config file at %s\n. Aborting" % 
                                CONFIG_LOCATION)
               sys.exit(1)
    else:
        nmconfig = NotmuchClientConfig()
        
    if nmconfig.remote:
        try:
            if not os.path.isdir(nmconfig.cache):
                os.mkdir(nmconfig.cache)
        except OSError:
            sys.stdout.write("Can't make cache file at %s" % nmconfig.cache)
    args = sys.argv[1:]
    command = NotmuchCommand.make_command(nmconfig, args)
    process = command.run()

    while True:
        nextline = process.stdout.readline()
        if (nextline == '' and  process.poll != None):
            break
        sys.stdout.write(nextline)
        sys.stdout.flush()

    sys.stderr.write(process.stderr.read())
    sys.stderr.flush()

